### ISSUE TITLE
Thunderbird doesn't build on i386 and arm32

### ISSUE THREAD

**Issue by AdrianKoshka** [flathub/org.mozilla.Thunderbird#6]

**Comment by ovari** [comment]
Document how to cross-compile
https://github.com/flatpak/flatpak/issues/5

Another option is “A collection of scripts for setting up build machines and running builds”
https://github.com/flatpak/flatpak-build-scripts

https://github.com/flatpak/flatpak-build-scripts/blob/master/build.conf
```
# Uncomment and set it to a supported architecture name
# when cross building to a host compatible cpu architecture,
# if not specified then the value of `flatpak --default-arch`
# will be used.
#
#BUILD_ARCH=i386
#
# Alternatively, if you want a single machine to build
# multiple arches, uncomment and set them in the following
# array:
#
#BUILD_ARCHES=(x86_64 i386)
```

Does this help you?

**Comment by AdrianKoshka** [comment]
I know how to build for `i386`, I just can't remember what went wrong, but it does help a bit.

**Comment by AdrianKoshka** [comment]
Also, you can already build for other arches with the current `Makefile`. What you need to do it `make BUILD_OPTIONS="--arch=i386"` for example. I did this recently for the barrrier flatpak i'm working on.

**Comment by AdrianKoshka** [comment]
So right, after trying to compile for `i386`, I get to thunderbird and this happens:

```
========================================================================
Building module thunderbird in /home/adrian/org.mozilla.Thunderbird/.flatpak-builder/build/thunderbird-1
========================================================================
Running: make -f client.mk
mkdir -p '/run/build/thunderbird/obj-i686-pc-linux-gnu/'
> /run/build/thunderbird/obj-i686-pc-linux-gnu/.mozconfig.mk
Adding client.mk options from /run/build/thunderbird/mozconfig:
    FOUND_MOZCONFIG := /run/build/thunderbird/mozconfig
make[1]: Entering directory '/run/build/thunderbird'
cd /run/build/thunderbird/obj-i686-pc-linux-gnu
/run/build/thunderbird/configure
Creating Python environment
New python executable in /run/build/thunderbird/obj-i686-pc-linux-gnu/_virtualenv/bin/python2.7
Also creating executable in /run/build/thunderbird/obj-i686-pc-linux-gnu/_virtualenv/bin/python
Installing setuptools, pip, wheel...done.
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-i686-2.7
creating build/temp.linux-i686-2.7/psutil
i586-unknown-linux-gcc -m32 -march=i586 -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/srv/sdkbuilder/work/build/i386/freedesktop-sdk-base-1-6/build/i386/tmp-glibc/work/i586-unknown-linux/python/2.7.12-r1=/usr/src/debug/python/2.7.12-r1 -fdebug-prefix-map=/srv/sdkbuilder/work/build/i386/freedesktop-sdk-base-1-6/build/i386/tmp-glibc/sysroots/x86_64-linux= -fdebug-prefix-map=/srv/sdkbuilder/work/build/i386/freedesktop-sdk-base-1-6/build/i386/tmp-glibc/sysroots/qemux86= -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=311 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-i686-2.7/psutil/_psutil_linux.o
psutil/_psutil_linux.c: In function ‘init_psutil_linux’:
psutil/_psutil_linux.c:652:54: warning: overflow in implicit constant conversion [-Woverflow]
     PyModule_AddIntConstant(module, "RLIM_INFINITY", RLIM_INFINITY);
                                                      ^~~~~~~~~~~~~
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/psutil
i586-unknown-linux-gcc -m32 -march=i586 -shared -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now build/temp.linux-i686-2.7/psutil/_psutil_linux.o -L/usr/lib -lpython2.7 -o build/lib.linux-i686-2.7/psutil/_psutil_linux.so
building 'psutil._psutil_posix' extension
i586-unknown-linux-gcc -m32 -march=i586 -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/srv/sdkbuilder/work/build/i386/freedesktop-sdk-base-1-6/build/i386/tmp-glibc/work/i586-unknown-linux/python/2.7.12-r1=/usr/src/debug/python/2.7.12-r1 -fdebug-prefix-map=/srv/sdkbuilder/work/build/i386/freedesktop-sdk-base-1-6/build/i386/tmp-glibc/sysroots/x86_64-linux= -fdebug-prefix-map=/srv/sdkbuilder/work/build/i386/freedesktop-sdk-base-1-6/build/i386/tmp-glibc/sysroots/qemux86= -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c psutil/_psutil_posix.c -o build/temp.linux-i686-2.7/psutil/_psutil_posix.o
i586-unknown-linux-gcc -m32 -march=i586 -shared -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now build/temp.linux-i686-2.7/psutil/_psutil_posix.o -L/usr/lib -lpython2.7 -o build/lib.linux-i686-2.7/psutil/_psutil_posix.so
copying build/lib.linux-i686-2.7/psutil/_psutil_linux.so -> psutil
copying build/lib.linux-i686-2.7/psutil/_psutil_posix.so -> psutil

Reexecuting in the virtualenv
Adding configure options from /run/build/thunderbird/mozconfig
  --prefix=/app
  --with-pthreads
  --disable-crashreporter
  --disable-debug
  --disable-gconf
  --disable-necko-wifi
  --disable-tests
  --disable-updater
  --enable-application=mail
  --enable-calendar
  --enable-gio
  --enable-install-strip
  --enable-official-branding
  --enable-optimize
  --enable-safe-browsing
  --enable-strip
  --enable-url-classifier
  --enable-pie
  --enable-system-ffi
  --enable-system-pixman
  --with-system-bz2
  --with-system-icu
  --with-system-jpeg
  --with-system-libvpx
  --with-system-zlib
checking for a shell... /usr/bin/sh
checking for host system type... i686-pc-linux-gnu
checking for target system type... i686-pc-linux-gnu
checking whether cross compiling... no
checking for pkg_config... /usr/bin/pkg-config
checking for pkg-config version... 0.29.1
checking for yasm... /usr/bin/yasm
checking yasm version... 1.3.0
checking for the target C compiler... /usr/bin/gcc
checking whether the target C compiler can be used... yes
checking the target C compiler version... 6.2.0
checking the target C compiler works... yes
checking for the target C++ compiler... /usr/bin/g++
checking whether the target C++ compiler can be used... yes
checking the target C++ compiler version... 6.2.0
checking the target C++ compiler works... yes
checking for the host C compiler... /usr/bin/gcc
checking whether the host C compiler can be used... yes
checking the host C compiler version... 6.2.0
checking the host C compiler works... yes
checking for the host C++ compiler... /usr/bin/g++
checking whether the host C++ compiler can be used... yes
checking the host C++ compiler version... 6.2.0
checking the host C++ compiler works... yes
checking for 64-bit OS... no
checking for stdint.h... yes
checking for inttypes.h... yes
checking for malloc.h... yes
checking for alloca.h... yes
checking for sys/byteorder.h... no
checking for getopt.h... yes
checking for unistd.h... yes
checking for nl_types.h... yes
checking for cpuid.h... yes
checking for sys/statvfs.h... yes
checking for sys/statfs.h... yes
checking for sys/vfs.h... yes
checking for sys/mount.h... yes
checking for sys/quota.h... yes
checking for linux/quota.h... yes
checking for linux/if_addr.h... yes
checking for linux/rtnetlink.h... yes
checking for sys/queue.h... yes
checking for sys/types.h... yes
checking for netinet/in.h... yes
checking for byteswap.h... yes
checking for linux/perf_event.h... yes
checking for perf_event_open system call... yes
checking whether the C compiler supports -Wclass-varargs... no
checking whether the C++ compiler supports -Wclass-varargs... no
checking whether the C compiler supports -Wloop-analysis... no
checking whether the C++ compiler supports -Wloop-analysis... no
checking whether the C++ compiler supports -Wc++11-compat-pedantic... no
checking whether the C++ compiler supports -Wc++14-compat... yes
checking whether the C++ compiler supports -Wc++14-compat-pedantic... no
checking whether the C++ compiler supports -Wc++1z-compat... no
checking whether the C++ compiler supports -Wimplicit-fallthrough... no
checking whether the C compiler supports -Wstring-conversion... no
checking whether the C++ compiler supports -Wstring-conversion... no
checking whether the C compiler supports -Wthread-safety... no
checking whether the C++ compiler supports -Wthread-safety... no
checking whether the C++ compiler supports -Wno-inline-new-delete... no
checking whether the C compiler supports -Wno-error=maybe-uninitialized... yes
checking whether the C++ compiler supports -Wno-error=maybe-uninitialized... yes
checking whether the C compiler supports -Wno-error=deprecated-declarations... yes
checking whether the C++ compiler supports -Wno-error=deprecated-declarations... yes
checking whether the C compiler supports -Wno-error=array-bounds... yes
checking whether the C++ compiler supports -Wno-error=array-bounds... yes
checking for libffi > 3.0.9... yes
checking MOZ_FFI_CFLAGS... -I/usr/lib/libffi-3.2.1/include
checking MOZ_FFI_LIBS... -lffi
checking for pango >= 1.22.0 pangoft2 >= 1.22.0 pangocairo >= 1.22.0... yes
checking MOZ_PANGO_CFLAGS... -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libpng16
checking MOZ_PANGO_LIBS... -lpangoft2-1.0 -lfontconfig -lfreetype -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lcairo
checking for fontconfig >= 2.7.0... yes
checking _FONTCONFIG_CFLAGS... -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking _FONTCONFIG_LIBS... -lfontconfig -lfreetype
checking for freetype2 >= 6.1.0... yes
checking _FT2_CFLAGS... -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking _FT2_LIBS... -lfreetype
checking for tar... /usr/bin/gtar
checking for unzip... /usr/bin/unzip
checking for zip... /usr/bin/zip
checking for the Mozilla API key... no
checking for the Google API key... no
checking for the Bing API key... no
checking for the Adjust SDK key... no
checking for awk... /usr/bin/gawk
checking for perl... /usr/bin/perl
checking for minimum required perl version >= 5.006... 5.022001
checking for full perl installation... yes
checking for gmake... /usr/bin/make
checking for doxygen... not found
checking for xargs... /usr/bin/xargs
checking for rpmbuild... not found
checking for autoconf... /app/bin/autoconf-2.13
creating cache ./config.cache
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking build system type... i686-pc-linux-gnu
checking for objcopy... /usr/bin/objcopy
checking for gcc... /usr/bin/gcc -std=gnu99
checking whether the C compiler (/usr/bin/gcc -std=gnu99 -O2 -g -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -L/app/lib ) works... yes
checking whether the C compiler (/usr/bin/gcc -std=gnu99 -O2 -g -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -L/app/lib ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether /usr/bin/gcc -std=gnu99 accepts -g... yes
checking for c++... /usr/bin/g++ -std=gnu++11
checking whether the C++ compiler (/usr/bin/g++ -std=gnu++11 -O2 -g -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -L/app/lib ) works... yes
checking whether the C++ compiler (/usr/bin/g++ -std=gnu++11 -O2 -g -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -L/app/lib ) is a cross-compiler... no
checking whether we are using GNU C++... yes
checking whether /usr/bin/g++ -std=gnu++11 accepts -g... yes
checking for ranlib... ranlib
checking for as... /usr/bin/as
checking for ar... ar
checking for ld... ld
checking for strip... strip
checking for windres... no
checking for otool... no
checking for X... libraries , headers 
checking for dnet_ntoa in -ldnet... no
checking for dnet_ntoa in -ldnet_stub... no
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking for --noexecstack option to as... yes
checking for -z noexecstack option to ld... yes
checking for -z text option to ld... yes
checking for --build-id option to ld... yes
checking for --ignore-unresolved-symbol option to ld... yes
checking if toolchain supports -mssse3 option... yes
checking if toolchain supports -msse4.1 option... yes
checking for x86 AVX2 asm support in compiler... yes
checking for PIE support... yes
checking for working const... yes
checking for mode_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking whether 64-bits std::atomic requires -latomic... no
checking for dirent.h that defines DIR... yes
checking for opendir in -ldir... no
checking for sockaddr_in.sin_len... false
checking for sockaddr_in6.sin6_len... false
checking for sockaddr.sa_len... false
checking for gethostbyname_r in -lc_r... no
checking for library containing dlopen... -ldl
checking for dlfcn.h... yes
checking for dladdr... yes
checking for memmem... yes
checking for socket in -lsocket... no
checking for XDrawLines in -lX11... yes
checking for XextAddDisplay in -lXext... yes
checking for XtFree in -lXt... yes
checking for xcb_connect in -lxcb... yes
checking for xcb_shm_query_version in -lxcb-shm... yes
checking for XGetXCBConnection in -lX11-xcb... yes
checking for X11/extensions/scrnsaver.h... yes
checking for XScreenSaverQueryInfo in -lXss... yes
checking for pthread_create in -lpthreads... no
checking for pthread_create in -lpthread... yes
checking whether /usr/bin/gcc -std=gnu99 accepts -pthread... yes
checking for pthread.h... yes
checking whether /usr/bin/gcc -std=gnu99 needs -traditional... no
checking for 8-bit clean memcmp... yes
checking for stat64... yes
checking for lstat64... yes
checking for truncate64... yes
checking for statvfs64... yes
checking for statvfs... yes
checking for statfs64... yes
checking for statfs... yes
checking for getpagesize... yes
checking for gmtime_r... yes
checking for localtime_r... yes
checking for arc4random... no
checking for arc4random_buf... no
checking for mallinfo... yes
checking for gettid... no
checking for lchown... yes
checking for setpriority... yes
checking for strerror... yes
checking for syscall... yes
checking for clock_gettime(CLOCK_MONOTONIC)... 
checking for pthread_cond_timedwait_monotonic_np... 
checking for wcrtomb... yes
checking for mbrtowc... yes
checking for res_ninit()... yes
checking for iconv in -lc... yes
checking for iconv()... yes
checking for iconv() with const input... no
checking for nl_langinfo and CODESET... yes
checking for an implementation of va_copy()... yes
checking whether va_list can be copied by value... yes
checking whether the C++ "using" keyword resolves ambiguity... yes
checking for C++ dynamic_cast to void*... yes
checking for __thread keyword for TLS variables... yes
checking for __attribute__((always_inline))... yes
checking for LC_MESSAGES... yes
checking for localeconv... yes
checking for malloc.h... yes
checking for strndup... yes
checking for posix_memalign... yes
checking for memalign... yes
checking for malloc_usable_size... yes
checking whether malloc_usable_size definition can use const argument... no
checking for valloc in malloc.h... yes
checking for valloc in unistd.h... no
checking NSPR selection... source-tree
checking for jpeg_destroy_compress in -ljpeg... yes
checking for gzread in -lz... yes
checking for BZ2_bzread in -lbz2... yes
checking if app-specific confvars.sh exists... /run/build/thunderbird/mozilla/../mail/confvars.sh
checking for gtk+-3.0 >= 3.4.0 gtk+-unix-print-3.0 glib-2.0 gobject-2.0 ... yes
checking MOZ_GTK3_CFLAGS... -pthread -I/usr/include/gtk-3.0/unix-print -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking MOZ_GTK3_LIBS... -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
checking for gtk+-2.0 >= 2.18.0 gtk+-unix-print-2.0 glib-2.0 >= 2.22 gobject-2.0 gdk-x11-2.0... yes
checking MOZ_GTK2_CFLAGS... -pthread -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gtk-2.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking MOZ_GTK2_LIBS... -lgtk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lfontconfig -lfreetype -lgdk-x11-2.0 -lpangocairo-1.0 -lpango-1.0 -lcairo -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0
checking for gio-2.0 >= 2.22... yes
checking MOZ_GIO_CFLAGS... -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking MOZ_GIO_LIBS... -lgio-2.0 -lgobject-2.0 -lglib-2.0
checking for dbus-1 >= 0.60... yes
checking MOZ_DBUS_CFLAGS... -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include
checking MOZ_DBUS_LIBS... -ldbus-1
checking for dbus-glib-1 >= 0.60... yes
checking MOZ_DBUS_GLIB_CFLAGS... -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking MOZ_DBUS_GLIB_LIBS... -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0
checking for vpx >= 1.5.0... yes
checking MOZ_LIBVPX_CFLAGS... 
checking MOZ_LIBVPX_LIBS... -lvpx -lm
checking for vpx/vpx_decoder.h... yes
checking for vpx_codec_dec_init_ver in -lvpx... yes
checking for vpx_mem/vpx_mem.h... no
checking for libpulse... yes
checking MOZ_PULSEAUDIO_CFLAGS... -D_REENTRANT
checking MOZ_PULSEAUDIO_LIBS... -lpulse
checking for linux/joystick.h... yes
checking for wget... no
checking for valid C compiler optimization flags... yes
checking whether linker creates PT_GNU_RELRO segments... yes
configure: warning: Disabling elfhack
checking for __cxa_demangle... yes
checking for unwind.h... yes
checking for _Unwind_Backtrace... yes
checking for -pipe support... yes
checking whether C compiler supports -fprofile-generate... yes
checking what kind of list files are supported by the linker... linkerscript
checking what kind of ordering can be done with the linker... section-ordering-file
checking for glib-2.0 >= 1.3.7 gobject-2.0... yes
checking GLIB_CFLAGS... -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
checking GLIB_LIBS... -lgobject-2.0 -lglib-2.0
checking for FT_Bitmap_Size.y_ppem... yes
checking for FT_GlyphSlot_Embolden... yes
checking for FT_Load_Sfnt_Table... yes
checking for fontconfig/fcfreetype.h... yes
checking for pixman-1 >= 0.19.2... yes
checking MOZ_PIXMAN_CFLAGS... -I/usr/include/pixman-1
checking MOZ_PIXMAN_LIBS... -lpixman-1
checking for icu-i18n >= 58.1... yes
checking MOZ_ICU_CFLAGS... 
checking MOZ_ICU_LIBS... -L/app/lib -licui18n -licuuc -licudata
checking for posix_fadvise... yes
checking for posix_fallocate... yes
updating cache ./config.cache
creating ./config.data
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
ValueError: semaphore or lock released too many times
```

**Comment by AdrianKoshka** [comment]
and if I `CRTL+C` to cancel the build:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
    rrelease()
ValueError: semaphore or lock released too many times
^CTraceback (most recent call last):
  File "/run/build/thunderbird/configure.py", line 32, in <module>
Traceback (most recent call last):
  File "/run/build/thunderbird/configure.py", line 32, in <module>
    sys.exit(main(sys.argv))
      File "/run/build/thunderbird/configure.py", line 24, in main
sys.exit(main(sys.argv))
  File "/run/build/thunderbird/configure.py", line 24, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 363, in run
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 334, in run
    func(*args)
      File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 406, in _value_for
self.include_file(path)
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
        exec_(code, self)
return self._value_for_depends(obj, need_help_dependency)
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/util.py", line 59, in exec_
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/util.py", line 925, in method_call
    exec(object, globals, locals)
  File "/run/build/thunderbird/moz.configure", line 7, in <module>
    include('mozilla/moz.configure')
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 627, in include_impl
    cache[args] = self.func(instance, *args)
    self.include_file(what)
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 416, in _value_for_depends
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
    exec_(code, self)
      File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/util.py", line 59, in exec_
return obj.result
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/util.py", line 943, in __get__
    exec(object, globals, locals)
  File "/run/build/thunderbird/mozilla/moz.configure", line 7, in <module>
    include('build/moz.configure/init.configure')
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 627, in include_impl
    setattr(instance, name, self.func(instance))
      File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 90, in result
self.include_file(what)
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
    return self.func(*resolved_args)
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/configure/__init__.py", line 932, in wrapped
    exec_(code, self)
  File "/run/build/thunderbird/mozilla/python/mozbuild/mozbuild/util.py", line 59, in exec_
Makefile:8: recipe for target 'build' failed
make: *** [build] Interrupt
```

**Comment by AdrianKoshka** [comment]
@ovari Do you know (or know anyone) who's fairly familiar with Thunderbirds' build process?

**Comment by ovari** [comment]
Windows Daily users please switch to 64bit builds
https://groups.google.com/forum/#!topic/tb-planning/Ya7TYVCWw8M

Mozilla Build
https://treeherder.mozilla.org/#/jobs?repo=comm-central

Have you subscribed to tb-planning?
https://wiki.mozilla.org/Thunderbird/tb-planning
https://mail.mozilla.org/listinfo/tb-planning

"Do you know (or know anyone) who's fairly familiar with Thunderbirds' build process?"
@AdrianKoshka Yes. Please contact by direct email if you want more details.

**Comment by AdrianKoshka** [comment]
I'll subscribe, also, is Thunderbird going to be abandoning 32-bit builds?

**Comment by ovari** [comment]
[Thunderbird 60.0b7](https://www.thunderbird.net/en-US/thunderbird/beta/all/) supports 32-bit.

Firefox 61.0b12 has both [32-bit](https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux) and [64-bit](https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64).

Perhaps you could email tb-planning about the future of 32-bit builds? What do you think?

**Comment by AdrianKoshka** [comment]
I think that'd be a good idea, I'll do this.

**Comment by ovari** [comment]
Do the links below help?
https://flathub.org/builds/#/builders/2/builds/2397

arm
https://flathub.org/builds/#/builders/43/builds/221

i386
https://flathub.org/builds/#/builders/20/builds/260

**Comment by AdrianKoshka** [comment]
Nope, I know full-well how to build things for the platform(s) I need to. The issue is Thunderbird _wont build_. I need someone who can help me diagnose _why_ it won't build.

**Comment by Erick555** [comment]
i386 is being dropped with 19.08 runtime release which is around the corner. 32bit arm si going to be dropped with 20.08 next year. That means supporting those has no future.
